import 'dotenv/config';
import {execFileSync} from 'node:child_process';

const ADB=process.env.ADB_PATH||'adb';
const API=(process.env.HARSHA_API_URL||'').replace(/\/$/,'');
const SECRET=process.env.FORENSIC_BRIDGE_SECRET||'';
function adb(args){return execFileSync(ADB,args,{encoding:'utf8',timeout:30000,windowsHide:true}).trim()}
function lines(s){return s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
function suspicious(s){return /(metasploit|frida|burp|zanti|droidsheep|termux|packetcapture|wireshark|nmap|sqlmap|hydra|netcat|keylogger|spy|rat|stealer|payload|exploit)/i.test(s)}
function parsePackages(){return lines(adb(['shell','pm','list','packages','-f'])).map(x=>{const m=x.match(/^package:(.+)=([^=]+)$/);const pkg=m?.[2]||x.replace(/^package:/,'');return {name:pkg,package:pkg,system:!x.includes('/data/app/'),suspicious:suspicious(pkg),category:suspicious(pkg)?'Review':'Installed'}})}
function parsePs(){return lines(adb(['shell','ps','-A'])).slice(1).map(x=>{const p=x.split(/\s+/);const name=p.at(-1)||'';return {pid:p[1]||'',name,suspicious:suspicious(name),category:suspicious(name)?'Review':'Process'}})}
function queryContent(uri,fields){try{const out=adb(['shell','content','query','--uri',uri,'--projection',fields]);return lines(out).map(x=>{const o={};for(const m of x.split(', ')){const i=m.indexOf('=');if(i>0)o[m.slice(0,i)]=m.slice(i+1)}return o})}catch{return[]}}
function collect(){const serial=adb(['get-state'])==='device'?adb(['get-serialno']):'';if(!serial)throw new Error('No authorized ADB device connected');const props=adb(['shell','getprop']);const model=props.match(/\[ro\.product\.model\]: \[([^\]]+)/)?.[1]||'Android device';const manufacturer=props.match(/\[ro\.product\.manufacturer\]: \[([^\]]+)/)?.[1]||'Android';const android=props.match(/\[ro\.build\.version\.release\]: \[([^\]]+)/)?.[1]||'—';const apps=parsePackages();const processes=parsePs();const sms=queryContent('content://sms',['address','body','date']);const contacts=queryContent('content://contacts/phones',['display_name','number']);let files=[];try{files=lines(adb(['shell','find','/sdcard','-maxdepth','2','-type','f'])).slice(0,500).map(path=>({path,suspicious:suspicious(path)}))}catch{}const findings=[];apps.filter(x=>x.suspicious).forEach(x=>findings.push({severity:'REVIEW',title:'Suspicious application indicator',detail:`Package name matched a forensic review heuristic: ${x.package}`}));processes.filter(x=>x.suspicious).forEach(x=>findings.push({severity:'REVIEW',title:'Suspicious running process indicator',detail:`Process matched a forensic review heuristic: ${x.name}`}));sms.forEach(x=>{x.suspicious=suspicious(`${x.address||''} ${x.body||''}`)});sms.filter(x=>x.suspicious).forEach(x=>findings.push({severity:'REVIEW',title:'Suspicious SMS indicator',detail:`Message from ${x.address||'unknown'} matched a review heuristic`}));return {device:{model,manufacturer,android,serial},apps,sms,contacts,files,processes,findings,scannedAt:new Date().toISOString()}}
try{if(!API||!SECRET)throw new Error('Set HARSHA_API_URL and FORENSIC_BRIDGE_SECRET in bridge/.env');const scan=collect();const r=await fetch(`${API}/api/scan`,{method:'POST',headers:{'content-type':'application/json','x-bridge-secret':SECRET},body:JSON.stringify(scan)});console.log(await r.text());if(!r.ok)process.exitCode=1}catch(e){console.error(`SCAN FAILED: ${e.message}`);process.exitCode=1}
